# fly.toml file generated for bowman-home on 2023-05-14T22:27:33-04:00

app = "bowman-home"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "yyz"
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "bowman-home.fly.dev"
  PORT = "8080"
  PRIMARY_REGION = "yyz"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = []
  entrypoint = []
  exec = []

[[services]]
  http_checks = []
  internal_port = 8080
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
